version: '2'

services:

  master1:
    build:
      context: master
      dockerfile: Dockerfile
      args:
         PORT: 7001
    network_mode: "host"

  master2:
    build:
      context: master
      dockerfile: Dockerfile
      args:
         PORT: 7002
    network_mode: "host"

  master3:
    build:
      context: master
      dockerfile: Dockerfile
      args:
         PORT: 7003

    network_mode: "host"

  slave1:
    build:
      context: master
      dockerfile: Dockerfile
      args:
         PORT: 7004
    network_mode: "host"

  slave2:
    build:
      context: master
      dockerfile: Dockerfile
      args:
         PORT: 7005
    network_mode: "host"

  slave3:
    build:
      context: master
      dockerfile: Dockerfile
      args:
         PORT: 7006
    network_mode: "host"
